# importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# importing the dataset

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
X = dataset.iloc[:,[2,3]].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [4]:
y = dataset.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

# splitting the dataset into the training set and test set

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

# feature scaling

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc_X = StandardScaler()
sc_X

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
X_train

array([[    40, 142000],
       [    47,  30000],
       [    38,  71000],
       [    21,  16000],
       [    32,  18000],
       [    39,  73000],
       [    47,  43000],
       [    27, 137000],
       [    36, 144000],
       [    35,  50000],
       [    35,  61000],
       [    19,  26000],
       [    59,  42000],
       [    40,  78000],
       [    40,  60000],
       [    45,  22000],
       [    39, 106000],
       [    28,  87000],
       [    32, 120000],
       [    22,  18000],
       [    46,  59000],
       [    36,  50000],
       [    40,  75000],
       [    38,  61000],
       [    47, 113000],
       [    30, 135000],
       [    27,  84000],
       [    47,  20000],
       [    49,  36000],
       [    47,  47000],
       [    51, 134000],
       [    30, 107000],
       [    55, 130000],
       [    21,  88000],
       [    37,  74000],
       [    46,  32000],
       [    42,  64000],
       [    27,  58000],
       [    28,  79000],
       [    51,  23000],


In [10]:
X_train = sc_X.fit_transform(X_train)
X_train

C:\Users\user.DESKTOP-HGCB2QF\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\user.DESKTOP-HGCB2QF\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.21772144,  2.03126521],
       [ 0.8727573 , -1.22247769],
       [ 0.03056834, -0.03137538],
       [-1.56023302, -1.62919555],
       [-0.53089096, -1.571093  ],
       [ 0.12414489,  0.02672717],
       [ 0.8727573 , -0.8448111 ],
       [-0.99877372,  1.88600883],
       [-0.15658476,  2.08936776],
       [-0.25016131, -0.64145217],
       [-0.25016131, -0.32188814],
       [-1.74738612, -1.33868279],
       [ 1.9956759 , -0.87386238],
       [ 0.21772144,  0.17198355],
       [ 0.21772144, -0.35093941],
       [ 0.68560419, -1.45488789],
       [ 0.12414489,  0.98541928],
       [-0.90519717,  0.43344504],
       [-0.53089096,  1.39213714],
       [-1.46665647, -1.571093  ],
       [ 0.77918075, -0.37999069],
       [-0.15658476, -0.64145217],
       [ 0.21772144,  0.08482973],
       [ 0.03056834, -0.32188814],
       [ 0.8727573 ,  1.18877821],
       [-0.71804407,  1.82790628],
       [-0.99877372,  0.34629121],
       [ 0.8727573 , -1.51299045],
       [ 1.0599104 ,

In [12]:
X_test = sc_X.transform(X_test)
X_test

array([[-3.53123668, -2.09403038],
       [-3.53123668, -2.09401772],
       [-3.69761152, -2.09401941],
       [-3.5837761 , -2.09400168],
       [-3.6450721 , -2.09403038],
       [-3.54874982, -2.09405739],
       [-3.49621039, -2.09403375],
       [-3.32983555, -2.09404135],
       [-3.48745382, -2.09402194],
       [-3.51372353, -2.0939637 ],
       [-3.59253267, -2.09400928],
       [-3.52248011, -2.09403375],
       [-3.68009838, -2.09400422],
       [-3.54874982, -2.09401181],
       [-3.5837761 , -2.0940211 ],
       [-3.40864468, -2.09395358],
       [-3.46994068, -2.09404388],
       [-3.54874982, -2.0940135 ],
       [-3.56626296, -2.09405063],
       [-3.57501953, -2.09396286],
       [-3.42615783, -2.09405317],
       [-3.49621039, -2.09401603],
       [-3.68885495, -2.09401266],
       [-3.49621039, -2.09403291],
       [-3.53123668, -2.09395526],
       [-3.56626296, -2.09401856],
       [-3.57501953, -2.09406161],
       [-3.41740126, -2.09404641],
       [-3.42615783,

# fitting logistic regression to the traning set

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
classifier = LogisticRegression(random_state = 0)
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
classifier.fit(X_train, y_train)
classifier

C:\Users\user.DESKTOP-HGCB2QF\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

# predicting the test set result

In [16]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

# making the confusion matrix

In [17]:
from sklearn.metrics import confusion_matrix

In [20]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[70,  0],
       [30,  0]], dtype=int64)

# virsualising the training set result

In [ ]:
from matplotlib.colors import ListedColormap